Remove leak error in HomeScreenFragment during Settings Clear
systers/malaria-app-android pull request #294
Opened 2018-04-22 11:40 UTC by DipanshKhandelwal

### Description
Remove leak error in HomeScreenFragment in Settings Clear Dialog

Fixes #274 

### Type of Change:
- Code: Dismiss dialog in onStop method.

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Any dependent changes have been published in downstream modules

2018-04-22 14:14 UTC, m-murad requested changes

2018-04-22 14:14 UTC, m-murad commented on malaria-app-android/src/main/java/com/peacecorps/malaria/fragment/HomeScreenFragment.java
> +    public void onStop() {
There is no guarantee that the `onStop` method will be called when we leave an activity. You need to move the code to `onPause` method.
For more info please read - https://developer.android.com/reference/android/app/Activity.html

2018-04-22 14:17 UTC, DipanshKhandelwal commented on malaria-app-android/src/main/java/com/peacecorps/malaria/fragment/HomeScreenFragment.java
> +    public void onStop() {
@m-murad Oh sorry. I'll do it.

2018-04-22 14:26 UTC, DipanshKhandelwal commented
@m-murad Please take a look.

2018-08-19 17:33 UTC, ExactlyMay commented
please send a new pr with the updated code from master. thank you!

2018-08-19 17:33 UTC, closed without merging