Fix pmd violations
systers/malaria-app-android pull request #315
Opened 2018-06-09 06:05 UTC by aayushinigam

Fixes #314 

Removed all the necessary pmd code rule violations - only 10/140 pmd violations exist now.
![screenshot from 2018-06-09 11-28-29](https://user-images.githubusercontent.com/24635221/41188311-09515076-6bd9-11e8-99b9-adf57fc420c5.png)

2018-06-09 06:09 UTC, aayushinigam commented
Base branch is changed because develop doesn't contain code from gsoc18-infra which has the code for pmd plugins.

2018-06-19 08:38 UTC, roopalJazz commented
Can you delete the .idea directory and again send the PR?

2018-06-19 08:40 UTC, r00pal requested changes
Delete the  .idea directory and remove the conflicts

2018-06-19 14:13 UTC, aayushinigam commented
@roopalJazz Sure! I will do that.

2018-07-12 16:30 UTC, geekanamika requested changes
Hey @aayushinigam lease remove .idea files, fetch the latest code from `gsoc18-code` branch and update PR.

2018-07-16 13:33 UTC, aayushinigam commented on malaria-app-android/src/main/java/com/peacecorps/malaria/db/DatabaseSQLiteHelper.java
> +        if (isDataFound && !(date.get(date.size() - 1) == Calendar.getInstance().get(Calendar.DATE))) {
This is how it was already existing in the codebase. Do I need to change it?

2018-07-17 14:08 UTC, roopalJazz commented on malaria-app-android/src/main/java/com/peacecorps/malaria/db/DatabaseSQLiteHelper.java
> +        if (isDataFound && !(date.get(date.size() - 1) == Calendar.getInstance().get(Calendar.DATE))) {
No

2018-07-17 14:12 UTC, r00pal approved these changes

2018-07-17 14:12 UTC, geekanamika commented on malaria-app-android/src/main/java/com/peacecorps/malaria/db/DatabaseSQLiteHelper.java
> +        if (isDataFound && !(date.get(date.size() - 1) == Calendar.getInstance().get(Calendar.DATE))) {
This file has been deleted in `gsoc18-code` since we've shifted to Room for malaria-android.

2018-07-24 07:42 UTC, aayushinigam commented on malaria-app-android/src/main/java/com/peacecorps/malaria/db/DatabaseSQLiteHelper.java
> +        if (isDataFound && !(date.get(date.size() - 1) == Calendar.getInstance().get(Calendar.DATE))) {
I fetched code from gsoc18-infra. Is pmd configured in gsoc-18 branch?

2018-07-28 16:29 UTC, geekanamika commented on malaria-app-android/src/main/java/com/peacecorps/malaria/db/DatabaseSQLiteHelper.java
> +        if (isDataFound && !(date.get(date.size() - 1) == Calendar.getInstance().get(Calendar.DATE))) {
It's not configured. Can you include it in PR too? Create an issue for including PMD in `gsoc18-code`
.

2018-08-04 12:23 UTC, geekanamika commented
@aayushinigam This PR can't be merged in latest code due to major infrastructure changes
As you're already working on `available` issues , closing it :)

2018-08-04 12:23 UTC, closed without merging